# Generated by Django 2.0.1 on 2018-02-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_text', models.CharField(max_length=1000)),
                ('send_time', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('time_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(verbose_name='date created')),
                ('last_active', models.DateTimeField(verbose_name='last active date')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='U1F92A.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='content_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='U1F92A.Photo'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='U1F92A.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='U1F92A.User'),
        ),
    ]
