# Generated by Django 2.0.1 on 2018-02-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U1F92A', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=10000),
        ),
    ]
