# Generated by Django 2.0.2 on 2018-02-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U1F92A', '0002_auto_20180210_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='base64',
        ),
    ]
